{% set name = "libmamba" %}
{% set version = "0.7.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/TheSnakePit/mamba/archive/{{ version }}.tar.gz
  sha256: 4c0553f09f9974f9a8316ec441db486f2f71d56d4a1e9e377b23b8e5296e2e1d

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
  host:
    - libsolv >=0.7.16
    - libcurl
    - openssl
    - libarchive
    - nlohmann_json
    - cpp-filesystem
    - yaml-cpp
    - reproc-cpp >=14.2.1

test:
  commands:
    - test -f $PREFIX/lib/libmamba${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/mamba/context.hpp  # [unix]
    - test -f $PREFIX/include/mamba/channel.hpp  # [unix]
    - if exist %LIBRARY_INC%\mamba\channel.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_INC%\mamba\context.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_LIB%\mamba.lib (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_BIN%\mamba.dll (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/TheSnakePit/mamba
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A library that exposes the internals of mamba, a fast drop-in alternative to conda
  description: A fast drop-in alternative to conda, using libsolv for dependency resolution
  dev_url: https://github.com/TheSnakePit/mamba

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - wolfv
